[package]
name = "hp_tr_finder"
version = "0.2.1"
edition = "2024"
description = "minimap2 frontend"
license = "MIT"
repository ="https://github.com/keithyin/hp_tr_finder"


[dependencies]
regex = "1"
intervaltree = "0.2.7"